http:
  port: "8081"
  
sfdc:
  username: "lakshmir@njclabs.com"
  password: "Lr710_@@"
  token: "sqYLzSruJzqmeediWz3Xhducr"
  
file:
  Dir: "D:/ZipFile/APDevFundamentals4.4_studentFiles_SP_27jun2022/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"